package gcp

import (
	"fmt"
	"strings"
)

// PrebuiltLlamaServerCUDA is the official llama.cpp CUDA server image we thin-wrap.
// Cold start = pull + start (no first-boot compile, no Cloud Build required).
const PrebuiltLlamaServerCUDA = "ghcr.io/ggml-org/llama.cpp:server-cuda"

// ImageConfig drives Dockerfile + entrypoint generation for llama-server.
// No ADC, service-account JSON, or Bearer is baked into the image.
type ImageConfig struct {
	// ModelID is the Hugging Face repo (org/name). Empty → runtime MODEL_ID env.
	ModelID string
	// GGUFFile optional preferred filename inside the repo.
	GGUFFile string
	// Port is the llama-server listen port (default 8080).
	Port int
	// IdleSeconds after last request before the entrypoint stops the VM.
	// 0 with KeepUp=true means never auto-stop.
	IdleSeconds int
	// KeepUp disables the idle watcher (IdleSeconds forced to 0).
	KeepUp bool
	// Context tokens for llama-server (-c).
	Context int
	// GPULayers (-ngl); -1 = all.
	GPULayers int
}

func (c ImageConfig) withDefaults() ImageConfig {
	if c.Port <= 0 {
		c.Port = ServerPort
	}
	if c.KeepUp {
		c.IdleSeconds = 0
	} else if c.IdleSeconds <= 0 {
		c.IdleSeconds = 600 // 10m stop-on-idle
	}
	if c.Context <= 0 {
		// OpenCode agent prompts routinely exceed 8k; 32k fits Qwen-class GGUFs.
		c.Context = 32768
	}
	if c.GPULayers == 0 {
		c.GPULayers = -1
	}
	return c
}

// Dockerfile returns a thin wrap of the official CUDA llama-server image plus
// our entrypoint (HF download + Bearer + stop-on-idle). Secrets are injected
// at runtime via env/metadata — never baked in.
func Dockerfile(cfg ImageConfig) string {
	cfg = cfg.withDefaults()
	var b strings.Builder
	b.WriteString(`# Generated by runhug — llama.cpp (llama-server) ONLY.
# Do NOT bake ADC, service-account keys, or API Bearer tokens into this image.
# Auth: CLI-managed Bearer via env API_KEY / metadata; bind 127.0.0.1; IAP tunnel.
# Cold start = pull + start (wraps prebuilt ` + PrebuiltLlamaServerCUDA + `).
FROM ` + PrebuiltLlamaServerCUDA + `
USER root
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
      curl ca-certificates python3 python3-pip iproute2 \
    && pip3 install --no-cache-dir --break-system-packages "huggingface_hub" \
    && rm -rf /var/lib/apt/lists/*
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV HOST=127.0.0.1 \
    PORT=` + fmt.Sprintf("%d", cfg.Port) + ` \
    IDLE_SECONDS=` + fmt.Sprintf("%d", cfg.IdleSeconds) + ` \
    CONTEXT=` + fmt.Sprintf("%d", cfg.Context) + ` \
    NGL=` + fmt.Sprintf("%d", cfg.GPULayers) + ` \
    MODEL_DIR=/models
# Optional build-time hints (overridable at runtime; never secrets):
`)
	if cfg.ModelID != "" {
		b.WriteString("ENV MODEL_ID=" + shellQuote(cfg.ModelID) + "\n")
	}
	if cfg.GGUFFile != "" {
		b.WriteString("ENV GGUF_FILE=" + shellQuote(cfg.GGUFFile) + "\n")
	}
	b.WriteString(`EXPOSE ` + fmt.Sprintf("%d", cfg.Port) + `
ENTRYPOINT ["/entrypoint.sh"]
`)
	return b.String()
}

// EntrypointScript downloads a GGUF (if needed), starts llama-server on
// 127.0.0.1 with a runtime API_KEY, and stop-on-idle shuts the VM down.
func EntrypointScript(cfg ImageConfig) string {
	cfg = cfg.withDefaults()
	return `#!/usr/bin/env bash
# Generated by runhug — llama-server entrypoint.
# Soft locks: bind 127.0.0.1, Bearer from env/metadata (not baked), stop-on-idle.
set -euo pipefail

META_BASE="http://metadata.google.internal/computeMetadata/v1"
meta_attr() {
  curl -sf -H "Metadata-Flavor: Google" \
    "${META_BASE}/instance/attributes/$1" 2>/dev/null || true
}

HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-` + fmt.Sprintf("%d", cfg.Port) + `}"
IDLE_SECONDS="${IDLE_SECONDS:-` + fmt.Sprintf("%d", cfg.IdleSeconds) + `}"
CONTEXT="${CONTEXT:-` + fmt.Sprintf("%d", cfg.Context) + `}"
NGL="${NGL:--1}"
MODEL_DIR="${MODEL_DIR:-/models}"
MODEL_ID="${MODEL_ID:-}"
GGUF_FILE="${GGUF_FILE:-}"
HF_TOKEN="${HF_TOKEN:-${HUGGING_FACE_HUB_TOKEN:-}}"

# Prefer explicit API_KEY; else GCE metadata attribute runhug-api-key (CLI-set).
if [[ -z "${API_KEY:-}" ]]; then
  API_KEY="$(meta_attr runhug-api-key)"
fi
if [[ -z "${API_KEY:-}" ]]; then
  echo "runhug: API_KEY / metadata runhug-api-key required (CLI-managed Bearer)" >&2
  exit 1
fi

# Optional: HF token + model hints from instance metadata (CLI metadata-from-file).
if [[ -z "$HF_TOKEN" ]]; then
  HF_TOKEN="$(meta_attr runhug-hf-token)"
fi
if [[ -z "$MODEL_ID" ]]; then
  MODEL_ID="$(meta_attr runhug-model-id)"
fi
if [[ -z "$GGUF_FILE" ]]; then
  GGUF_FILE="$(meta_attr runhug-gguf-file)"
fi

mkdir -p "$MODEL_DIR"
GGUF_PATH="${GGUF_PATH:-}"

download_model() {
  if [[ -z "$MODEL_ID" ]]; then
    echo "runhug: MODEL_ID (HF repo) required" >&2
    exit 1
  fi
  local args=(download "$MODEL_ID")
  if [[ -n "$GGUF_FILE" ]]; then
    args+=("$GGUF_FILE")
  fi
  args+=(--local-dir "$MODEL_DIR")
  if [[ -n "$HF_TOKEN" ]]; then
    export HF_TOKEN HUGGING_FACE_HUB_TOKEN="$HF_TOKEN"
    args+=(--token "$HF_TOKEN")
  fi
  echo "runhug: fetching ${MODEL_ID}${GGUF_FILE:+ ($GGUF_FILE)} …" >&2
  hf "${args[@]}"
  if [[ -n "$GGUF_FILE" && -f "$MODEL_DIR/$GGUF_FILE" ]]; then
    GGUF_PATH="$MODEL_DIR/$GGUF_FILE"
    return
  fi
  GGUF_PATH="$(MODEL_DIR="$MODEL_DIR" python3 -c '
import os, glob
pref = ["q4_k_m","q5_k_m","q4_k_s","iq4_xs","q4_0","q5_0","q3_k_m","q6_k","q8_0"]
root = os.environ["MODEL_DIR"]
files = [f for f in glob.glob(root + "/**/*.gguf", recursive=True)
         if "mmproj" not in f.lower() and "imatrix" not in f.lower()]
if not files:
    raise SystemExit("no .gguf found under " + root)
best, score = files[0], -1
for f in files:
    low = f.lower()
    for i, q in enumerate(pref):
        if q in low:
            s = len(pref) - i
            if s > score:
                best, score = f, s
            break
print(best)
')"
}

if [[ -z "$GGUF_PATH" || ! -f "$GGUF_PATH" ]]; then
  download_model
fi

# Prefer PATH; official CUDA images may install under /app.
if ! command -v llama-server >/dev/null 2>&1; then
  if [[ -x /app/llama-server ]]; then
    PATH="/app:${PATH}"
    export PATH
  fi
fi

echo "runhug: llama-server $GGUF_PATH on ${HOST}:${PORT} (idle=${IDLE_SECONDS}s)" >&2
ARGS=(-m "$GGUF_PATH" --host "$HOST" --port "$PORT" -c "$CONTEXT" -ngl "$NGL" --api-key "$API_KEY")
if [[ -n "${SERVED_MODEL:-}" ]]; then
  ARGS+=(--alias "$SERVED_MODEL")
elif [[ -n "$MODEL_ID" ]]; then
  ARGS+=(--alias "$MODEL_ID")
fi

llama-server "${ARGS[@]}" &
SERVER_PID=$!

# IDLE_SECONDS <= 0 (keep-up): no auto-stop — operator must runhug gcp stop.
if [[ "${IDLE_SECONDS}" =~ ^[0-9]+$ ]] && [[ "$IDLE_SECONDS" -gt 0 ]]; then
  LAST_OK="$(date +%s)"
  echo "$LAST_OK" >/tmp/runhug-last-request
  (
    while kill -0 "$SERVER_PID" 2>/dev/null; do
      now="$(date +%s)"
      peers="$(ss -tn "sport = :${PORT}" state established 2>/dev/null | awk 'NR>1{c++} END{print c+0}')"
      peers="${peers:-0}"
      if [[ "$peers" -gt 0 ]]; then
        LAST_OK="$now"
        echo "$now" >/tmp/runhug-last-request
      fi
      if [[ $((now - LAST_OK)) -ge "$IDLE_SECONDS" ]]; then
        echo "runhug: idle ${IDLE_SECONDS}s — stopping VM" >&2
        kill "$SERVER_PID" 2>/dev/null || true
        TOK="$(curl -sf -H "Metadata-Flavor: Google" "$META_BASE/instance/service-accounts/default/token" | python3 -c 'import sys,json; print(json.load(sys.stdin).get("access_token",""))' 2>/dev/null || true)"
        PROJ="$(curl -sf -H "Metadata-Flavor: Google" "$META_BASE/project/project-id" 2>/dev/null || true)"
        ZONE="$(curl -sf -H "Metadata-Flavor: Google" "$META_BASE/instance/zone" 2>/dev/null | awk -F/ '{print $NF}' || true)"
        NAME="$(curl -sf -H "Metadata-Flavor: Google" "$META_BASE/instance/name" 2>/dev/null || true)"
        if [[ -n "$TOK" && -n "$PROJ" && -n "$ZONE" && -n "$NAME" ]]; then
          curl -sf -X POST -H "Authorization: Bearer $TOK" \
            "https://compute.googleapis.com/compute/v1/projects/${PROJ}/zones/${ZONE}/instances/${NAME}/stop" >/dev/null || true
        elif command -v shutdown >/dev/null 2>&1; then
          shutdown -h now || poweroff || true
        else
          poweroff || true
        fi
        exit 0
      fi
      sleep 15
    done
  ) &
else
  echo "runhug: keep-up — stop-on-idle disabled (runhug gcp stop when done)" >&2
fi

wait "$SERVER_PID"
`
}

// StartupScript boots a Spot GPU VM and runs the prebuilt container with docker.
// Soft locks: 127.0.0.1 + Bearer from metadata + stop-on-idle (inside entrypoint).
// create-with-container was discontinued by GCP; Phase 1 uses instances create + docker.
func StartupScript(cfg ImageConfig) string {
	cfg = cfg.withDefaults()
	_ = cfg
	return `#!/usr/bin/env bash
# Generated by runhug — Spot GPU docker launcher (no first-boot llama compile).
set -euo pipefail
exec > >(tee -a /var/log/runhug-startup.log) 2>&1
echo "runhug: startup begin $(date -Is)"

META="http://metadata.google.internal/computeMetadata/v1"
meta_attr() {
  curl -sf -H "Metadata-Flavor: Google" "${META}/instance/attributes/$1" || true
}

IMAGE="$(meta_attr runhug-container-image)"
if [[ -z "$IMAGE" ]]; then
  echo "runhug: metadata runhug-container-image required" >&2
  exit 1
fi
MODEL_ID="$(meta_attr runhug-model-id)"
GGUF_FILE="$(meta_attr runhug-gguf-file)"
IDLE_SECONDS="$(meta_attr runhug-idle-seconds)"
IDLE_SECONDS="${IDLE_SECONDS:-600}"

# Wait for NVIDIA first (DLVM installs drivers on boot).
for i in $(seq 1 60); do
  if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi >/dev/null 2>&1; then
    nvidia-smi -L || true
    break
  fi
  sleep 5
done

# DLVM does not always ship docker; install Engine + NVIDIA Container Toolkit.
ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    return 0
  fi
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y --no-install-recommends ca-certificates curl gnupg
  if ! command -v docker >/dev/null 2>&1; then
    # Official Docker CE (amd64) — needed for --gpus via nvidia-container-toolkit.
    install -m 0755 -d /etc/apt/keyrings
    if [[ ! -f /etc/apt/keyrings/docker.asc ]]; then
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
    fi
    . /etc/os-release
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
      >/etc/apt/sources.list.d/docker.list
    apt-get update -y
    apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io
  fi
  systemctl enable --now docker || service docker start || true
  # NVIDIA Container Toolkit for --gpus all
  if ! dpkg -l nvidia-container-toolkit >/dev/null 2>&1; then
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
      | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
      >/etc/apt/sources.list.d/nvidia-container-toolkit.list
    apt-get update -y
    apt-get install -y --no-install-recommends nvidia-container-toolkit
    nvidia-ctk runtime configure --runtime=docker || true
    systemctl restart docker || service docker restart || true
  fi
  for i in $(seq 1 30); do
    if docker info >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  return 1
}

if ! ensure_docker; then
  echo "runhug: docker not available after install" >&2
  exit 1
fi

# Artifact Registry pull (ADC via instance SA + cloud-platform scope).
if command -v gcloud >/dev/null 2>&1; then
  REGISTRY="$(echo "$IMAGE" | cut -d/ -f1)"
  gcloud auth configure-docker "$REGISTRY" --quiet || true
elif command -v docker-credential-gcr >/dev/null 2>&1; then
  docker-credential-gcr configure-docker --registries="$(echo "$IMAGE" | cut -d/ -f1)" || true
fi

echo "runhug: pulling $IMAGE …"
docker pull "$IMAGE"

NAME="runhug-llama"
docker rm -f "$NAME" 2>/dev/null || true

ENV_ARGS=(-e HOST=127.0.0.1 -e PORT=8080 -e IDLE_SECONDS="$IDLE_SECONDS" -e CONTEXT=32768 -e NGL=-1)
if [[ -n "$MODEL_ID" ]]; then ENV_ARGS+=(-e "MODEL_ID=$MODEL_ID"); fi
if [[ -n "$GGUF_FILE" ]]; then ENV_ARGS+=(-e "GGUF_FILE=$GGUF_FILE"); fi

echo "runhug: docker run $IMAGE (host net, GPU, 127.0.0.1:8080)"
docker run -d --name "$NAME" --restart=no \
  --gpus all --network host --privileged \
  "${ENV_ARGS[@]}" \
  "$IMAGE"

echo "runhug: container started; entrypoint owns /v1 + stop-on-idle"
`
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// WriteImageFiles writes Dockerfile + entrypoint.sh into dir.
func WriteImageFiles(dir string, cfg ImageConfig) error {
	cfg = cfg.withDefaults()
	if err := writeFile(dir+"/Dockerfile", Dockerfile(cfg)); err != nil {
		return err
	}
	return writeFile(dir+"/entrypoint.sh", EntrypointScript(cfg))
}
