package gcp

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// ImageConfig drives Dockerfile + entrypoint generation for llama-server.
// No ADC, service-account JSON, or Bearer is baked into the image.
type ImageConfig struct {
	// ModelID is the Hugging Face repo (org/name). Empty → runtime MODEL_ID env.
	ModelID string
	// GGUFFile optional preferred filename inside the repo.
	GGUFFile string
	// Port is the llama-server listen port (default 8080).
	Port int
	// IdleSeconds after last request before the entrypoint stops the VM.
	IdleSeconds int
	// Context tokens for llama-server (-c).
	Context int
	// GPULayers (-ngl); -1 = all.
	GPULayers int
}

func (c ImageConfig) withDefaults() ImageConfig {
	if c.Port <= 0 {
		c.Port = ServerPort
	}
	if c.IdleSeconds <= 0 {
		c.IdleSeconds = 600 // 10m stop-on-idle
	}
	if c.Context <= 0 {
		c.Context = 8192
	}
	if c.GPULayers == 0 {
		c.GPULayers = -1
	}
	return c
}

// Dockerfile returns a CUDA runtime image that builds llama-server and runs
// the generated entrypoint. Secrets are injected at runtime via env/metadata.
func Dockerfile(cfg ImageConfig) string {
	cfg = cfg.withDefaults()
	var b strings.Builder
	b.WriteString(`# Generated by runhug — llama.cpp (llama-server) ONLY.
# Do NOT bake ADC, service-account keys, or API Bearer tokens into this image.
# Auth: CLI-managed Bearer via env API_KEY / metadata; bind 127.0.0.1; IAP tunnel.
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04 AS build
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential cmake git curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN git clone --depth 1 https://github.com/ggerganov/llama.cpp.git .
RUN cmake -B build -DGGML_CUDA=ON -DCMAKE_BUILD_TYPE=Release \
 && cmake --build build --config Release -j"$(nproc)" --target llama-server

FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
      curl ca-certificates python3 python3-pip \
    && pip3 install --no-cache-dir "huggingface_hub[cli]" \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /src/build/bin/llama-server /usr/local/bin/llama-server
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV HOST=127.0.0.1 \
    PORT=` + fmt.Sprintf("%d", cfg.Port) + ` \
    IDLE_SECONDS=` + fmt.Sprintf("%d", cfg.IdleSeconds) + ` \
    CONTEXT=` + fmt.Sprintf("%d", cfg.Context) + ` \
    NGL=` + fmt.Sprintf("%d", cfg.GPULayers) + ` \
    MODEL_DIR=/models
# Optional build-time hints (overridable at runtime; never secrets):
`)
	if cfg.ModelID != "" {
		b.WriteString("ENV MODEL_ID=" + shellQuote(cfg.ModelID) + "\n")
	}
	if cfg.GGUFFile != "" {
		b.WriteString("ENV GGUF_FILE=" + shellQuote(cfg.GGUFFile) + "\n")
	}
	b.WriteString(`EXPOSE ` + fmt.Sprintf("%d", cfg.Port) + `
ENTRYPOINT ["/entrypoint.sh"]
`)
	return b.String()
}

// EntrypointScript downloads a GGUF (if needed), starts llama-server on
// 127.0.0.1 with a runtime API_KEY, and stop-on-idle shuts the VM down.
func EntrypointScript(cfg ImageConfig) string {
	cfg = cfg.withDefaults()
	return `#!/usr/bin/env bash
# Generated by runhug — llama-server entrypoint.
# Soft locks: bind 127.0.0.1, Bearer from env/metadata (not baked), stop-on-idle.
set -euo pipefail

HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-` + fmt.Sprintf("%d", cfg.Port) + `}"
IDLE_SECONDS="${IDLE_SECONDS:-` + fmt.Sprintf("%d", cfg.IdleSeconds) + `}"
CONTEXT="${CONTEXT:-` + fmt.Sprintf("%d", cfg.Context) + `}"
NGL="${NGL:--1}"
MODEL_DIR="${MODEL_DIR:-/models}"
MODEL_ID="${MODEL_ID:-}"
GGUF_FILE="${GGUF_FILE:-}"
HF_TOKEN="${HF_TOKEN:-${HUGGING_FACE_HUB_TOKEN:-}}"

# Prefer explicit API_KEY; else GCE metadata attribute runhug-api-key (CLI-set).
if [[ -z "${API_KEY:-}" ]]; then
  API_KEY="$(curl -sf -H "Metadata-Flavor: Google" \
    "http://metadata.google.internal/computeMetadata/v1/instance/attributes/runhug-api-key" 2>/dev/null || true)"
fi
if [[ -z "${API_KEY:-}" ]]; then
  echo "runhug: API_KEY / metadata runhug-api-key required (CLI-managed Bearer)" >&2
  exit 1
fi

mkdir -p "$MODEL_DIR"
GGUF_PATH="${GGUF_PATH:-}"

download_model() {
  if [[ -z "$MODEL_ID" ]]; then
    echo "runhug: MODEL_ID (HF repo) required" >&2
    exit 1
  fi
  local args=(download "$MODEL_ID")
  if [[ -n "$GGUF_FILE" ]]; then
    args+=("$GGUF_FILE")
  fi
  args+=(--local-dir "$MODEL_DIR" --local-dir-use-symlinks False)
  if [[ -n "$HF_TOKEN" ]]; then
    export HF_TOKEN HUGGING_FACE_HUB_TOKEN="$HF_TOKEN"
  fi
  echo "runhug: fetching ${MODEL_ID}${GGUF_FILE:+ ($GGUF_FILE)} …" >&2
  huggingface-cli "${args[@]}"
  if [[ -n "$GGUF_FILE" && -f "$MODEL_DIR/$GGUF_FILE" ]]; then
    GGUF_PATH="$MODEL_DIR/$GGUF_FILE"
    return
  fi
  GGUF_PATH="$(MODEL_DIR="$MODEL_DIR" python3 -c '
import os, glob
pref = ["q4_k_m","q5_k_m","q4_k_s","iq4_xs","q4_0","q5_0","q3_k_m","q6_k","q8_0"]
root = os.environ["MODEL_DIR"]
files = [f for f in glob.glob(root + "/**/*.gguf", recursive=True)
         if "mmproj" not in f.lower() and "imatrix" not in f.lower()]
if not files:
    raise SystemExit("no .gguf found under " + root)
best, score = files[0], -1
for f in files:
    low = f.lower()
    for i, q in enumerate(pref):
        if q in low:
            s = len(pref) - i
            if s > score:
                best, score = f, s
            break
print(best)
')"
}

if [[ -z "$GGUF_PATH" || ! -f "$GGUF_PATH" ]]; then
  download_model
fi

echo "runhug: llama-server $GGUF_PATH on ${HOST}:${PORT} (idle=${IDLE_SECONDS}s)" >&2
ARGS=(-m "$GGUF_PATH" --host "$HOST" --port "$PORT" -c "$CONTEXT" -ngl "$NGL" --api-key "$API_KEY")
if [[ -n "${SERVED_MODEL:-}" ]]; then
  ARGS+=(--alias "$SERVED_MODEL")
elif [[ -n "$MODEL_ID" ]]; then
  ARGS+=(--alias "$MODEL_ID")
fi

llama-server "${ARGS[@]}" &
SERVER_PID=$!

LAST_OK="$(date +%s)"
echo "$LAST_OK" >/tmp/runhug-last-request
(
  while kill -0 "$SERVER_PID" 2>/dev/null; do
    now="$(date +%s)"
    peers="$(ss -tn "sport = :${PORT}" state established 2>/dev/null | wc -l | tr -d " " || echo 0)"
    if [[ "${peers:-0}" -gt 1 ]]; then
      LAST_OK="$now"
      echo "$now" >/tmp/runhug-last-request
    fi
    if [[ $((now - LAST_OK)) -ge "$IDLE_SECONDS" ]]; then
      echo "runhug: idle ${IDLE_SECONDS}s — stopping VM" >&2
      kill "$SERVER_PID" 2>/dev/null || true
      if command -v shutdown >/dev/null 2>&1; then
        shutdown -h now || poweroff || true
      else
        poweroff || true
      fi
      exit 0
    fi
    sleep 15
  done
) &

wait "$SERVER_PID"
`
}

// StartupScript is a GCE metadata startup-script that installs llama-server on
// a Deep Learning / CUDA VM and runs the same entrypoint. Secrets come from
// instance metadata only (never baked into a disk image).
func StartupScript(cfg ImageConfig) string {
	cfg = cfg.withDefaults()
	epB64 := base64.StdEncoding.EncodeToString([]byte(EntrypointScript(cfg)))
	modelLine := ""
	if cfg.ModelID != "" {
		modelLine = "export MODEL_ID=" + shellQuote(cfg.ModelID) + "\n"
	}
	ggufLine := ""
	if cfg.GGUFFile != "" {
		ggufLine = "export GGUF_FILE=" + shellQuote(cfg.GGUFFile) + "\n"
	}
	return `#!/usr/bin/env bash
# runhug GCE startup — Spot GPU llama-server (no secrets in image templates).
set -euo pipefail
exec > >(tee -a /var/log/runhug-startup.log) 2>&1

` + modelLine + ggufLine + `
export HOST=127.0.0.1
export PORT=` + fmt.Sprintf("%d", cfg.Port) + `
export IDLE_SECONDS=` + fmt.Sprintf("%d", cfg.IdleSeconds) + `
export CONTEXT=` + fmt.Sprintf("%d", cfg.Context) + `
export NGL=` + fmt.Sprintf("%d", cfg.GPULayers) + `
export MODEL_DIR=/var/lib/runhug/models
mkdir -p "$MODEL_DIR" /opt/runhug

export API_KEY="$(curl -sf -H "Metadata-Flavor: Google" \
  http://metadata.google.internal/computeMetadata/v1/instance/attributes/runhug-api-key || true)"
export HF_TOKEN="$(curl -sf -H "Metadata-Flavor: Google" \
  http://metadata.google.internal/computeMetadata/v1/instance/attributes/runhug-hf-token || true)"
export HUGGING_FACE_HUB_TOKEN="${HF_TOKEN:-}"

if [[ -z "${MODEL_ID:-}" ]]; then
  MODEL_ID="$(curl -sf -H "Metadata-Flavor: Google" \
    http://metadata.google.internal/computeMetadata/v1/instance/attributes/runhug-model-id || true)"
  export MODEL_ID
fi
if [[ -z "${GGUF_FILE:-}" ]]; then
  GGUF_FILE="$(curl -sf -H "Metadata-Flavor: Google" \
    http://metadata.google.internal/computeMetadata/v1/instance/attributes/runhug-gguf-file || true)"
  export GGUF_FILE
fi

if ! command -v llama-server >/dev/null 2>&1; then
  echo "runhug: installing llama-server …"
  apt-get update -y
  apt-get install -y --no-install-recommends curl ca-certificates python3 python3-pip git cmake build-essential iproute2
  pip3 install --no-cache-dir "huggingface_hub[cli]"
  cd /opt/runhug
  if [[ ! -d llama.cpp ]]; then
    git clone --depth 1 https://github.com/ggerganov/llama.cpp.git
  fi
  cd llama.cpp
  cmake -B build -DGGML_CUDA=ON -DCMAKE_BUILD_TYPE=Release
  cmake --build build --config Release -j"$(nproc)" --target llama-server
  install -m 755 build/bin/llama-server /usr/local/bin/llama-server
fi
command -v huggingface-cli >/dev/null 2>&1 || pip3 install --no-cache-dir "huggingface_hub[cli]"
command -v ss >/dev/null 2>&1 || apt-get install -y --no-install-recommends iproute2

echo '` + epB64 + `' | base64 -d >/opt/runhug/entrypoint.sh
chmod +x /opt/runhug/entrypoint.sh
date +%s >/tmp/runhug-last-request
exec /opt/runhug/entrypoint.sh
`
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// WriteImageFiles writes Dockerfile + entrypoint.sh into dir.
func WriteImageFiles(dir string, cfg ImageConfig) error {
	cfg = cfg.withDefaults()
	if err := writeFile(dir+"/Dockerfile", Dockerfile(cfg)); err != nil {
		return err
	}
	return writeFile(dir+"/entrypoint.sh", EntrypointScript(cfg))
}
